rlabbe/Kalman-and-Bayesian-Filters-in-Python

00_Preface.ipynb

This is a really trivial issue.

Trivial issue: fixed broken link on the Installation appendix.

---

01_g-h_filter.ipynb

* Fixed a few very small issues I found while reading the chapter.
Signed-off-by: mr.Shu <mr@shu.io>

g-h_filter: Small changes

---

01_g-h_filter.ipynb

Removed extra blank line. Added missed dots at the ending of sentences.

The g-h Filter: trivial formating issues

---

05_Kalman_Filters.ipynb

Description refers to the green line.
> So the output of the sensor should be a wavering dotted red line drawn over a straight green line. The green line shows the actual position of the dog, and the dotted red line is the noisy signal produced by the simulated RFID sensor. Please note that the red dotted line was manually plotted - we do not yet have a filter that recovers that information!
But the plot shows black instead.
P.S. May be the description is correct, and error in the plot?

One Dimensional Kalman Filters: wrong color of curve in plot description

---

05_Kalman_Filters.ipynb

One Dimensional Kalman Filters: fixed typo in code snippet of multiplying of Gaussians.

---

styles/custom2.css

If anything goes wrong, please tell me and I'll debug it for you. Sorry if you feel like I'm wasting your time, but I think it's important to fix this bug properly.

Fix issue #16 properly without centered headers

---

13-Smoothing.ipynb

I found a small typo in this chapter, figured I'd just submit a patch since it is so small.
I think "than" should be "then" in one sentence. Also added a comma. 
If I made a mistake, my apologies :-)

Fix typo in 13-Smoothing

---

01-g-h-filter.ipynb
03-Gaussians.ipynb
04-One-Dimensional-Kalman-Filters.ipynb
05-Multivariate-Gaussians.ipynb
06-Multivariate-Kalman-Filters.ipynb
07-Kalman-Filter-Math.ipynb

Found some more typos and mistakes.
I corrected some of the KF equations in chap. 6, the superscripts/bars were not always used consistently.
Please review.

More fixes for chap. 1, 3, 4, 5, 6, 7

---

03-Gaussians.ipynb

* integrals should have "du", etc. (right??)
* $\mathit{VAR}$ gives better spacing than $VAR$
* I find "within $1\sigma$" to be ambiguous; "within $\pm1sigma$" much more clear
* Changed dashes in text from hyphens to em-dashes
* Changed (some) straight quotation marks to curly ones (and removed single quotes in favour of double ones)
* Improved "°C" to just use a text symbol
* Assorted random typos, etc., but avoided rewording anything except for one particularly difficult sentence

03-gaussians copyedit

---

06-Multivariate-Kalman-Filters.ipynb

Trying to fix broken layout (layout at http://nbviewer.jupyter.org is broken) of 6 Chapter.

Trying to fix broken layout.

---

04-One-Dimensional-Kalman-Filters.ipynb

Added one missing closing bracket in `04-One-Dimensional-Kalman-Filters.ipynb`, section **Code Walkthrough**.

Added missing closing bracket.

---

13-Smoothing.ipynb

python code does apply transpose as is correct in RTS

Missing transpose in text

---

05-Multivariate-Gaussians.ipynb

I _believe_ these changes are correct, at the very least they made more sense to me this way!

Fix a couple of typos found in Chapter 5.

---

05-Multivariate-Gaussians.ipynb

Essentially changed two words in the text. Please feel free to change them if they do not reflect what you wanted to convay. 
Thanks.

Fixed two typos in notebook 5 Multivariate Gaussians.

---

07-Kalman-Filter-Math.ipynb

Hello Mr rlabbe, I found a minor mistake in one of your formulas in the Math chapter. Thank you for your great job. 
Mario Cano
Universidad Nacional de Colombia
Medellín

Fixed formula in Kalman Filter Math

---

README.md

Now the title of this file is rendered correctly.

Fix formation in heading in README.md

---

07-Kalman-Filter-Math.ipynb

Changed stoochastic to stochastic.

Fixed typo in Chapter 7

---

04-One-Dimensional-Kalman-Filters.ipynb

Fixed text describing Gaussian prediction calculation, in particular changed to use sigma, instead of mu when describing the variance update.

Fixed text describing Gaussian prediction calculation

---

Supporting_Notebooks/Computing_and_plotting_PDFs.ipynb

The function we use ist $f(x)=2x+12$, not $f(x)=2x+1$.

Typo correction

---

README.md

Adding a link to README.md that makes it easy for users to launch this repository in Azure Notebooks

Add launch in Azure Notebooks button

---

01-g-h-filter.ipynb

- Exercise Bad Initial Conditions: update the condition with the solution
- Exercise Extreme Noise: update solution parameter h to 0.01 (same as previous ex.)

01-g-h-filter.ipynb: minor fix

---

04-One-Dimensional-Kalman-Filters.ipynb

Found a type-o

---

07-Kalman-Filter-Math.ipynb
08-Designing-Kalman-Filters.ipynb

Found two minor Errors.
Thanks for the great Book.

minor fixes

---

08-Designing-Kalman-Filters.ipynb

A fix for #226 
Just remove the dot

Fix a typo in Chapter 8

---

08-Designing-Kalman-Filters.ipynb

The vector H is wrong for the velocity measurement.
The code of the subsequent example is correct though.

Fix another typo in Chapter 8

---

01-g-h-filter.ipynb

Fixed typo

---

04-One-Dimensional-Kalman-Filters.ipynb

Fix bug and use more intuitive example

Update content of 04-One-Dimensional-Kalman-Filters

---

00-Preface.ipynb
01-g-h-filter.ipynb

fix: Fix typo

---

00-Preface.ipynb
01-g-h-filter.ipynb
02-Discrete-Bayes.ipynb
03-Gaussians.ipynb
04-One-Dimensional-Kalman-Filters.ipynb
05-Multivariate-Gaussians.ipynb
06-Multivariate-Kalman-Filters.ipynb
07-Kalman-Filter-Math.ipynb
08-Designing-Kalman-Filters.ipynb
09-Nonlinear-Filtering.ipynb
10-Unscented-Kalman-Filter.ipynb
11-Extended-Kalman-Filters.ipynb
12-Particle-Filters.ipynb
13-Smoothing.ipynb
14-Adaptive-Filtering.ipynb
Appendix-D-HInfinity-Filters.ipynb
Appendix-E-Ensemble-Kalman-Filters.ipynb
Appendix-G-Designing-Nonlinear-Kalman-Filters.ipynb
Appendix-H-Least-Squares-Filters.ipynb
Appendix-I-Analytic-Evaluation-of-Performance.ipynb
Supporting_Notebooks/Computing_and_plotting_PDFs.ipynb
Supporting_Notebooks/Converting-Multivariate-Equations-to-Univariate.ipynb
Supporting_Notebooks/Interactions.ipynb
Supporting_Notebooks/Iterative-Least-Squares-for-Sensor-Fusion.ipynb
Supporting_Notebooks/Taylor-Series.ipynb

Bug fix: moved __future__ import to the top

---

environment.yml

solves issue [# 317](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/issues/317).

fix: add pip as dependency to env yml

---

02-Discrete-Bayes.ipynb
03-Gaussians.ipynb
04-One-Dimensional-Kalman-Filters.ipynb
05-Multivariate-Gaussians.ipynb
06-Multivariate-Kalman-Filters.ipynb
07-Kalman-Filter-Math.ipynb
08-Designing-Kalman-Filters.ipynb
09-Nonlinear-Filtering.ipynb
10-Unscented-Kalman-Filter.ipynb
11-Extended-Kalman-Filters.ipynb
12-Particle-Filters.ipynb
13-Smoothing.ipynb
14-Adaptive-Filtering.ipynb
Appendix-A-Installation.ipynb
Appendix-B-Symbols-and-Notations.ipynb
Appendix-D-HInfinity-Filters.ipynb
Appendix-E-Ensemble-Kalman-Filters.ipynb
Appendix-G-Designing-Nonlinear-Kalman-Filters.ipynb
Appendix-H-Least-Squares-Filters.ipynb
Appendix-I-Analytic-Evaluation-of-Performance.ipynb

Opened the file in Jupyter Lab and saved it to get rid of the notebook validation error: Notebook validation failed as suggested in [this](https://github.com/jupyter-widgets/ipywidgets/issues/2788) thread.
The main differences are the version numbers at the end of the file.

Fix Notebook Validation error

---

README.md

It was using two RING OPERATOR but I changed it to DEGREE SIGN

Fix some typos, grammar

---

03-Gaussians.ipynb

I believe the word independent is duplicated here.

Minor typo
