02_Discrete_Bayes.ipynb

Maybe I'm wrong, but it seems to me that events in example of conditional probability were put vice-versa.

Discrete Bayes Filter: events in example of conditional probability are put vice-versa

---

01-g-h-filter.ipynb

Your book is amazing, thanks for sharing it! I've fixed several typos and updated (fixed?) one of the code samples. A couple of notes:
- When text disagreed with code and/or figures, I amended the text and left the code/figures alone (e.g. line 1753).
- Code sample #58 was printing `x` and `dx_0`, but I'm almost sure that was a typo because `x` wasn't defined in that sample. I'm assuming the intention was to print the output of the filter, and not the initial conditions.

Fixed typos, corrected code #58.

---

code/RobotLocalizationParticleFilter.py

Variable 'indexes' should be created as array of  type 'int'

Fix systemic_resample() float indexes bug

---

code/book_format.py

The ```s``` dictionary containing the JSON settings is being overwritten with the matplotlib version in line 127, resulting in:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-34-a550bbe40f47> in <module>()
7 sys.path.insert(0,'./code')
8 from book_format import load_style
----> 9 load_style()
/home/dragos/Projects/testkalmanbook/Kalman-and-Bayesian-Filters-in-Python/code/book_format.py in load_style(directory, name)
127 
128     if version[0] > 1 or (version[0] == 1 and version[1] >= 5):
--> 129         s["axes.prop_cycle"] = "cycler('color', ['#6d904f','#013afe', '#202020','#fc4f30','#e5ae38','#A60628','#30a2da','#008080','#7A68A6','#CF4457','#188487','#E24A33' …
```

Fixed JSON settings being overwritten with matplotlib version.

---

10-Unscented-Kalman-Filter.ipynb

This is really minor issue.
`State` and `mean` in this context are synonyms, so technically is nothing wrong with using mean, but in my opinion using the same terms as at previous para will be better.

Unscented Kalman Filter: using "state estimate" instead of "mean estimate" in the covariance equation at the predict step

---

code/mkf_internal.py

plt.scatter(...) can accept either 'c' or 'color' parameter but not both. This makes assert exception.

mkf_internal.py : Fix duplicated parameter in plt.scatter(...)

---

07-Kalman-Filter-Math.ipynb

I've fixed the inverse Laplace transform equation to compute \phi(t) in the Linear Time Invariant Theory section of Chapter 7. Instead of the state transition matrix F, the equation should have the system dynamics matrix A. 
Ref: Eq  4.2.2-10,  Estimation with Applications To Tracking and Navigation, Bar-Shalom Y, et.al, 2001

Chapter 7 Fix LTI system theory equation for phi(t)

---

04-One-Dimensional-Kalman-Filters.ipynb

Fixed process_model to have `m/s` as unit. 
Currently, process_model.mean has unit of `m` which is passed to DogSimulation object as velocity. Inside move method, velocity is multiplied with time step which makes unit as `m*s`.

Fixed Unit of process_model for First Kalman Filter in Chapter 4

---

06-Multivariate-Kalman-Filters.ipynb

If you search for `dt = 0.3` you will find that the actual `x` position will be 11.35 after *innovation* (I borrowed your word here) because it's `10 + 4.5*0.3`
I think you were mistaken that `dt = 0.2`.
I chose to change the value 10.90 in the text instead of changing `dt` to `0.2` because it would alter the output of the subsequent cells.

Change 10.90 to 11.35

---

01-g-h-filter.ipynb
kf_book/gh_internal.py

"weight" --> "estimate"
"initial_guess" --> "initial_estimate"
print_results: rename label "previous" --> "previous estimate", add comma
Since measurements, estimates, and predictions are all weights in this example, I found it difficult to follow the code given a variable named simply "weight".  Likewise, "initial_guess" for the newcomer isn't obviously an estimate (vs. say a prediction).  Finally in the printed output, I wasn't sure what "previous" was (measurement, estimate, or prediction).
I believe this change helps the example's clarity significantly.  Thank you for considering.

improve naming in ch 1 "predict_using_gain_guess" example

---

03-Gaussians.ipynb
04-One-Dimensional-Kalman-Filters.ipynb

* Fixes expected value for continuous function in Chap 3
* Fixes product of Gaussians in Chap 4
Closes #268, #234

Bug fix: Issues in Chap 3 and 4

---

01-g-h-filter.ipynb

In the Exercise: Write Generic Algorithm section the user gets an
error trying to run the cell after uncomment the call to the function
because the plot_g_h_results function is imported on the next cell
This fix makes the import in the previous cell, resolving the issue

Changing plot_g_h_results import line

---

README.md
environment.yml

tested with miniconda using conda version 4.6.12+
I got the following warning:
> Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

add pip requirement to conda env and update readme

---

11-Extended-Kalman-Filters.ipynb

"unknown character" was displayed instead of the "-" in the "in text" equation: "f(x) = x^2-2x"
for some reason i cannot verify if my modification fixes the problem, (can't view the rendered file on my forked branch, i am getting an error when loading the file...), but i'm pretty sure it's ok.

"typo" correction

---

03-Gaussians.ipynb

The factorization on the third line appears incorrect. Both terms should be positive after factoring out the negative sign.

incorrect sign in product of Gaussian derivation

---

README.md

`source` works for activation, but not for deactivation. `conda` works for both operations. This is also in line with the instructions from Anaconda.

Replace source command with conda command

---

02-Discrete-Bayes.ipynb

When running all code in chapter 2 (02-Discrete-Bayes.ipynb), then interacting with first slider (dog moving with perfect prediction) shows result of second interactive element (dog moving inperfect prediction). Also some other sliders show results for another slider. This PR fixes these errors by renaming variables to not conflict and upgrading step functions to utilize scopes.

Fix interactive elements in 02-Discrete-Bayes.ipynb

---

06-Multivariate-Kalman-Filters.ipynb

The equation was not consistent with the text "divide the uncertainty of the prior with the of the sum of the uncertainty of the prior and measurement".

correct the explanatory equation for Kalman gain

---

experiments/ILS.py
experiments/gauss.py
experiments/ukf_range.py
kf_book/book_plots.py

There are small typos in:
- experiments/ILS.py
- experiments/gauss.py
- experiments/ukf_range.py
- kf_book/book_plots.py
Fixes:
- Should read `standard` rather than `standand`.
- Should read `search` rather than `seach`.
- Should read `object` rather than `obect`.
- Should read `measurement` rather than `measurment`.
- Should read `consistent` rather than `consistant`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

06-Multivariate-Kalman-Filters.ipynb

Small typo in markdown cell of `06-Multivariate-Kalman-Filters.ipynb`.
- Changed `filtery.common` to `filterpy.common`.

Fix a typo
